version: '3.4'
services:
  crcr:
    container_name: crcr-webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - MEMORY_LIMIT=512M
    networks:
      - default
    ports:
      - 80:80      
    restart: always