version: '3.4'
services:
  cicrc:
    container_name: cicrc-webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    networks:
      - default
    ports:
      - 80:80
    restart: always